### ISSUE TITLE
Does lwrb_reset are thread safety?

### ISSUE THREAD

**Issue by lygstate** [MaJerle/lwrb#11]
I means the thread 1 are writing data, and thread 2 are calling to lwrb_reset,
does lwrb_reset  are thread safety?
,or in reverse mode
If this is not thread safety, how to getting it thread safety, in rare case, I need to calling lwrb_reset 
to reset the ring buffer

**Comment by MaJerle** [comment]
Thread safety is only guaranteed for read/write operation, and this only when one thread writes, and second reads

All other operations are not thread safe. If you also want to achieve thread safety for reset, then all, “read/write/reset” must have exclusive access. In practice it means that before you do read or write, you need to obtain exclusive access with mutex/semaphore/disable_interrupts (or any other option that guarantees this).

Reason behind is that write operations modify only write pointer and read operations only read pointer in the buffer structure. If you use “reset”, you are modifying both pointers, and this makes it non-thread safe.

**Comment by lygstate** [comment]
> Thread safety is only guaranteed for read/write operation, and this only when one thread writes, and second reads
> 
> All other operations are not thread safe. If you also want to achieve thread safety for reset, then all, “read/write/reset” must have exclusive access. In practice it means that before you do read or write, you need to obtain exclusive access with mutex/semaphore/disable_interrupts (or any other option that guarantees this).
> 
> Reason behind is that write operations modify only write pointer and read operations only read pointer in the buffer structure. If you use “reset”, you are modifying both pointers, and this makes it non-thread safe.

Good to see, maybe it's better to document which functions are thread safe

**Comment by MaJerle** [comment]
There are some docs here: https://docs.majerle.eu/projects/lwrb/en/latest/user-manual/thread-safety.html
