### ISSUE TITLE
extend API to avoid memcpy

### ISSUE THREAD

**Issue by edsiper** [MaJerle/lwrb#13]
I am wondering if you have considered a version of the API that avoids memory copy of the buffer. In our case we are interested to store pointers' addresses in the ring buffer, so avoiding memcpy might be ideal.

is it possible?

**Comment by MaJerle** [comment]
If you just want to store pointers in buffer, then store value of pointer to buffer.

```c
/* Variables definition */
uint8_t rb_ptrs_data[sizeof(void*) * number_of_ptrs_to_hold];
lwrb_t rb_ptrs;

/* Init sequence */
lwrb_init(&rb_ptrs, rb_ptrs_data, sizeof(rb_ptrs_data));

/* Writing */
your_type* ptr = malloc(...);
lwrb_write(&rb_ptrs, &ptr, sizeof(ptr));

/* Reading & freeing */
your_type* ptr;
lwrb_read(&rb_ptrs, (void *)&ptr, sizeof(ptr));
free(ptr);
```

Disclaimer: Code has been written w/o compilation test

**Comment by edsiper** [comment]
awesome, thanks for sharing this.
