### ISSUE TITLE
Remove useless sub-repositories to avoid pulling errors

### ISSUE THREAD

**Issue by Linjieqiang** [MaJerle/lwrb#21]
![cdcfa18e6bb3bdce005dbdb01cce273](https://user-images.githubusercontent.com/10217966/212804715-8911ab53-06f9-43f0-8cb2-4bb7485dc990.png)

![image](https://user-images.githubusercontent.com/10217966/212804742-3508d15b-0aa5-4876-b348-b3f4a8a40600.png)

**Comment by MaJerle** [comment]
If you know how to cleanup git cache with that - let me know.

Github support was not able to help
