### ISSUE TITLE
When storing non-8bi data, the reading does not match the actual data

### ISSUE THREAD

**Issue by caibirdfly** [MaJerle/lwrb#25]
1. The following code is an example of storing 16bit data,

Before the i=5 write operation: r_fifo->w = 30, r_fifo-r = 40, lwrb_get_free(&r_fifo)=9; after the write operation, r_fifo->w = 39, which is no longer a multiple of 2, then The buffer is full.
When i=6, the write data starts to be written from 39, the data transmission is misplaced, and the reading is not as expected.

```
  lwrb_t r_fifo;
   int16_t buf[25] = {0};
   lwrb_init(&r_fifo, buf, 25*2);
  
   int16_t abuf[25];
   int16_t cbuf[25];
   int i=0;
   for(;i<24;i++)
     abuf[i] = i+1;

   for(i=0;i<100;i++)
   {
     lwrb_write(&r_fifo,abuf,8*2);
     lwrb_read(&r_fifo,cbuf,4*2);
   }

```
Test and modify lwrb_write, add the code between /****/, which can store int16_t data. When the buffer is full, reading data is normal.
Do you see if the type of stored data needs to be added to the library.

```

size_t lwrb_write(lwrb_t* buff, const void* data, size_t btw) {

/*
*
*
*/
     /* Calculate maximum number of bytes available to write */
     free = lwrb_get_free(buff);

  /**************************************************** *****/
     if(free < btw)
     {
       if(free - sizeof(int16_t)+1<=0)
       {
         btw = 0;
       }
       else
       {
         btw = free - sizeof(int16_t)+1;
       }
     }
// btw = BUF_MIN(free, btw);
     /**************************************************** *****/

     if (btw == 0) {
         return 0;
     }
   
     /*
      *
      *
      */
   
}
```

2.By the way, how to use the lwrb_get_linear_block_read_address() function correctly, is it similar to the processing of lwrb_read(), read to the end, the data is not read, and then read from the head. Is there any good way to deal with it?

**Comment by MaJerle** [comment]
Buffer does now know which type of data you try to write. It only knows the pointer and length. And function will return you number of bytes written so you can compare what has been written versus what you wanted to write.

The use of `lwrb_get_linear_block_read_address` will give you a pointer to the `&buff[read]` that you can use to directly read by memcpy, or any other method. use `lwrb_get_linear_block_read_length` prior to that, to get number of bytes you can actually read.

Here some examples: https://docs.majerle.eu/projects/lwrb/en/latest/user-manual/hw-dma-usage.html

**Comment by caibirdfly** [comment]
Thanks for your answer.
I didn't understand` lwrb_get_linear_block_read_length` correctly before, and now it's no problem to use DMA.
The data type problem, I didn’t make it clear before, I write multiple int16_t data at a time, the above problem occurs, your answer gives me ideas, make a judgment before writing the data` if (lwrb_get_free(&rb) >= sizeof(uint16_t)*number_of_save )`, so that there is no error in storing the number.
