### ISSUE TITLE
Is `volatile` keyword necessery for local variables of functions?

### ISSUE THREAD

**Issue by adadaadadade** [MaJerle/lwrb#27]
Thank you for sharing the lib. And It helps me a lot.

I wonder Is the `volatile` necessery for local variables of functions. I mean `volatile` forces compiler to access variables directly and do not use registers for optimization. But these local variables are just temporaries of real values. And they are in stack or registers, unlike the real values in struct, nobody will change them.

**Comment by MaJerle** [comment]
It must be ensured, that variables don't change values in-between if statements.

**Comment by MaJerle** [comment]
Functions to get free and full numbers are most problematic.

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwrb/commit/4f00e0656cc89b3432fcd91a2e66ed8a08671dc9
