### ISSUE TITLE
Find not reaching last elements

### ISSUE THREAD

**Issue by leiba01** [MaJerle/lwrb#28]
I believe lwrb_find is not reaching all the way to the end of the buffer to find the needle.

The function is looping buff full - input len - start_offset, but I believe the condition in the foor loop should be <=.

**Comment by MaJerle** [comment]
Thanks for reporting. Do you have min reproducible code?

**Comment by MaJerle** [comment]
I confirm bug. It was fixed with release of 3.0.0
