### ISSUE TITLE
Design question: why not use a atomic struct?

### ISSUE THREAD

**Issue by g-berthiaume** [MaJerle/lwrb#32]
Hi Majerle,

Thanks for making this repo available. 
This is a great tool to understand how to solve concurency issue on microcontrollers.

I have a quick question about one of you design decision.

Instead of defining 2 atomic variables for the head and the tail.
```C
typedef struct lwrb {
    //...
    atomic_ulong r;
    atomic_ulong w; 
} lwrb_t;
```
Why not use a atomic struct ?
```C
typedef struct {
    long r;
    long w; 
} lwrb_internals_t;

typedef struct lwrb {
    //...
   _Atomic lwrb_internals_t internal;
} lwrb_t;
```

Wouldn't this approach remove the ambiguity in the `lwrb_get_full` and `lwrb_get_free` ? 
Maybe I'm overthinking it...

**Comment by MaJerle** [comment]
If we define full struct as atomic, then you always have to read/write full struct from/to memory in atomic mode. This is not necessary what we want.

There is no ambiguoty in mentioned functions.

**Comment by g-berthiaume** [comment]
Fair enough. 
Have a good day!
