### ISSUE TITLE
Atomic Compilation and Project Setup Issues in PlatformIO

### ISSUE THREAD

**Issue by ttchalakov** [MaJerle/lwrb#35]
Hello, for some context I saw this lib on the PlatformIO [registry](https://registry.platformio.org/libraries/majerle/LwRB) and would like to use it for a project with an Arduino Due. The registry page says it is at version 2.0.3 and has not been updated. It is specifically missing the following in its `library.json`:
```json
"build": {
     "includeDir": "lwrb/src/include",
     "srcDir": "lwrb/src/lwrb"
}
```
I am not sure if you maintain that registry anymore but I thought I would let you know. Otherwise, I specifically have 2 other question about compiling the project. I was able to submodule and compile the main stable branch with the following limitations.

### 1) Stable main branch throws error if `LWRB_DEV` is not defined.
I am not sure if this is intended but it might be preferable for the define statements to remove any of the development code if LWRB_DEV is not defined instead of throwing an error during compilation as including the `lwrb.h` will always make the compiler try to compile `lwrb_ex.c`.
```
#error "This file needs development & extensive tests - not to be used!"
  ^~~~~
```

### 2) Atomic lwrb does not compile for GCC arm-none-eabi 7.2.1.
The library compiles correctly when`LWRB_DISABLE_ATOMIC` is defined but produces the following errors when attempting to enable the atomic feature of the code.
```bash
In file included from lib/lwrb/lwrb/src/include/lwrb/lwrb.h:53:0,
                 from src/main.cpp:5:
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:49:9: error: '_Atomic' does not name a type
 typedef _Atomic unsigned long atomic_ulong;
         ^~~~~~~
...
```
(omitted for brevity as above repeats for all std:: types)
```
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:218:9: error: '_Atomic' does not name a type
 typedef _Atomic struct
         ^~~~~~~
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:225:3: error: 'atomic_flag' does not name a type; did you mean 'atomic_load'?
 } atomic_flag;
   ^~~~~~~~~~~
   atomic_load
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:230:8: error: '_Bool' does not name a type; did you mean 'Bool'?
 extern _Bool atomic_flag_test_and_set (volatile atomic_flag *);
        ^~~~~
        Bool
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:233:8: error: '_Bool' does not name a type; did you mean 'Bool'?
 extern _Bool atomic_flag_test_and_set_explicit (volatile atomic_flag *,
        ^~~~~
        Bool
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:238:41: error: 'atomic_flag' does not name a type; did you mean 'atomic_load'?
 extern void atomic_flag_clear (volatile atomic_flag *);
                                         ^~~~~~~~~~~
                                         atomic_load
.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/7.2.1/include/stdatomic.h:240:50: error: 'atomic_flag' does not name a type; did you mean 'atomic_load'?
 extern void atomic_flag_clear_explicit (volatile atomic_flag *, memory_order);
                                                  ^~~~~~~~~~~
                                                  atomic_load
In file included from src/main.cpp:5:0:
lib/lwrb/lwrb/src/include/lwrb/lwrb.h:54:9: error: 'atomic_ulong' does not name a type; did you mean 'atomic_load'?
 typedef atomic_ulong lwrb_ulong_t;
         ^~~~~~~~~~~~
         atomic_load
lib/lwrb/lwrb/src/include/lwrb/lwrb.h:85:5: error: 'lwrb_ulong_t' does not name a type
     lwrb_ulong_t r; /*!< Next read pointer. Buffer is considered empty when `r == w` and full when `w == r - 1` */
     ^~~~~~~~~~~~
lib/lwrb/lwrb/src/include/lwrb/lwrb.h:86:5: error: 'lwrb_ulong_t' does not name a type
     lwrb_ulong_t w; /*!< Next write pointer. Buffer is considered empty when `r == w` and full when `w == r - 1` */
```
The project correctly determines that the code is being compiled with c++ so the atomic code is wrapped in `extern "C" {}`. But this is where I was unable to figure out where why the compiler toolchain fails to define the `_Atomic` struct.

**Comment by MaJerle** [comment]
Hi @ttchalakov , my comments:

1. Correct, currently the `_ex.c` file isn't fully tested. I would suggest you to remove the file from your repository, so that it is not included in the build and it will be fine. Or simply delete the check and don't use the functions.

2. It seems that `_Atomic` keyword isn't supported in GCC7, which seems to only be the case if `C11` flag isn't enabled.

https://stackoverflow.com/questions/16256586/how-to-enable-c11-on-later-versions-of-gcc

**Comment by ttchalakov** [comment]
Hello, @MaJerle  thanks for the reply!

1. I will not use those functions.
2. My project will eventually have multiple threads writing to the buffer with one reader, but I might not need atomicity for that because my system is 32-bit and I will make the operations thread safe. I did try investigating using different [gcc toolchains](https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi) recommended for my platform and by setting `-std=c11` but continued to run into compilation errors. But this doesn't matter anymore. I can proceed without atomic being enabled. If you have tested this code on a microcontroller, what compiler did you use and any other options that you enabled?

Thanks for your help! Would be awesome if the PlatformIO registry got updated, I feel like other people would like to use this library through there!

**Comment by MaJerle** [comment]
1. It was a good time to bring this up. I released a new version `3.1.0` which adds some new features and removes error if `LWRB_DEV` isn't present.
2. Another option might be to use `gnu11`, but it also depends on which CPU you use (if that's supported on it). [Here](https://docs.majerle.eu/projects/lwrb/en/latest/user-manual/thread-safety.html) are some thread-safety considerations you may want to check before you decide. I am always using latest GCC version. Also please note that if you use the header in the C++ project, `_Atomic` doesn't work there.

**Comment by ttchalakov** [comment]
Thanks for the new version. I spent some time learning more about how C++ compilers handle a mix of C and C++ code because the Arduino framework requires using C++ if I would like to use the features in its API. The `extern "C"` block in `lwrb.h` enables me to link the C function headers, but as you said, enabling atomics won't work in my C++ project because it is a C library that uses `_Atomic` keyword. Do you plan on supporting C++ atomic operation with `<atomic>`? I can just throw a mutex around the lwrb as a solution in my project for now.

**Comment by MaJerle** [comment]
`stdatomic` in C and `atomic` in C++ are not necessarily binary compatible, therefore a completely new module shall be developed for C++ (`lwrb.cpp`). I have not considered this option as of now.

**Comment by ttchalakov** [comment]
Sounds great! Thanks for the help I have no further questions. Feel free to close this issue.
