### ISSUE TITLE
Lwrb Write and read data, whether MCU interrupt needs to be turned off or not

### ISSUE THREAD

**Issue by cqutyoulang** [MaJerle/lwrb#36]
MCU serial port interrupt to write data to Lwrb, using RTOS. read data from Lwrb in the task, need to turn off the interrupt for protection when writing and reading Lwrb?

**Comment by MaJerle** [comment]
Here some insights: https://docs.majerle.eu/projects/lwrb/en/latest/user-manual/thread-safety.html

You may not need to disable IRQ, if you use it correctly.

**Comment by cqutyoulang** [comment]
I have another question, in the link it describes the use of C11stdatomic to ensure that writes and reads are atomic. But my program is not normal C11, so I defined LWRB_DISABLE_ATOMIC to disable the atomic operation, so how should I use other ways to make sure that it is atomic (except the way to turn off interrupts), I'm using the STM32F407 chip

**Comment by MaJerle** [comment]
Normally it depends on the variable type size and architecture size. You are on Cortex-M4 and type is 32-bit, so you should be fine w/o atomic.

**Comment by cqutyoulang** [comment]
The stm32 is a 32 bit MCU, for data manipulation atomicity are 4 bytes, if I send a packet using lwrb, this packet is not 4 byte aligned but 1 byte aligned, write the data in interrupt and read the data in a thread without turning off the interrupt is there any problem.

**Comment by MaJerle** [comment]
You are mixing many things here. It is not about data, it is about the `LDR` and `STR` and other instructions, that operate on the `write` and `read` pointers.

You will be fine without disabling interrupts, provided you have one write point and one read point (PIPE mode) only.
