### ISSUE TITLE
included c header file in extern "C" section

### ISSUE THREAD

**Issue by Tizio1234** [MaJerle/lwrb#38]
In lwrb.h, inside the extern "C" section, there is a c header include, specifically `#include <stdatomic.h"`, when including this header file from c++ files, the included stdatomic.h is actually the cpp version, so it does not compile.
It is fixable by moving the include out of the extern "C" section.

**Comment by MaJerle** [comment]
Problem is more complex than this.

stdatomic.h in C is not binary compatible with atomic in C++. If you initiate lwrb_t in C++ object, it may have different structure than the one in C object and may not be binary compatible.

It is not advised to use atomicity feature in C++ projects.

**Comment by Tizio1234** [comment]
So lib can't work when using c++?

**Comment by Tizio1234** [comment]
Thank you for the assistance, should I close the issue?

**Comment by Tizio1234** [comment]
Could a #define LWRB_DISABLE_ATOMIC be useful inside the #ifdef __cplusplus section?

**Comment by MaJerle** [comment]
No. What matters is a compilation unit, and these are not compatible between C and C++, if we are strict. It would be an undefined behavior.

https://stackoverflow.com/questions/75868704/how-to-properly-mix-stdatomic-between-c-and-c

**Comment by Tizio1234** [comment]
So I should do #define LWRB_DISABLE_ATOMIC at the top of the header file?

**Comment by MaJerle** [comment]
The best would be you do it in the -D parameter to the compiler.
