### ISSUE TITLE
about BUF_IS_VALID(b) 

### ISSUE THREAD

**Issue by andykim-hub** [MaJerle/lwrb#4]
File lwrb.c
#define BUF_IS_VALID(b)                 ((b) != NULL && (b)->magic1 == BUF_MAGIC1 && (b)->magic2 == ~BUF_MAGIC2 && (b)->buff != NULL && (b)->size > 0)

should be 

#define BUF_IS_VALID(b)                 ((b) != NULL && (b)->magic1 == BUF_MAGIC1 && (b)->magic2 == BUF_MAGIC2 && (b)->buff != NULL && (b)->size > 0)

？
Otherwise, the judgment is wrong。

**Comment by MaJerle** [comment]
Fixed on develop branch.
