### ISSUE TITLE
can i use it in stm32 usart dma idle receive？

### ISSUE THREAD

**Issue by benzhiqiang** [MaJerle/lwrb#7]
can i use it in stm32 usart dma idle receive？receive data from dma，then put data in the ringbuff

**Comment by MaJerle** [comment]
Yes indeed.

See examples here: https://github.com/MaJerle/stm32-usart-uart-dma-rx-tx

**Comment by benzhiqiang** [comment]
I have read the code。I'm confused.Is it necessary to use dma HT、TC，IDLE IT at the same time？Assume dma buffer is 200bytes，HT is 100bytes，if receive 125bytes。First trigger HT IT ，we receive and process 100bytes，then trigger IDLE IT，we receive and process the last 25bytes。If no HT IT，we receive and process the 125bytes at one time，I find no difference between them。Maybe it is OK not to use dma HT TC IT。 Maybe there is something secret I don't understand。Could you explain it？Thank you。

**Comment by MaJerle** [comment]
Thats true, but only valid for your case. What if you receive 250 bytes in one shot? What happens with buffer at the beginning if you dont read it quick enough?

**Comment by benzhiqiang** [comment]
I think i understand why you use DMA HT TC IT.With only IDLE IT,when receive bytes more than DMA buffer,the last 50 bytes will cover the 50 bytes of the first received 200 bytes. 
The situation never occors to me, because I always make very big DMA buffer,far more than bytes need to  be received.
Thank you very much for your reply.

**Comment by MaJerle** [comment]
OK, I let you do it your way, but be careful. It may trigger errors for you.
You need HT, TC and IDLE events, all enabled. 

In circular mode, you don't reset DMA to 0 so it may happen your DMA starts processing big amount of bytes in the middle, and then you do need HT and TC events.
